---
- name: Install nginx Server
  hosts: aws1
  become: true
  tasks:
  - name: Install Nginx 
    yum:
      name: nginx
      state: present 

  - name: copy index.html
    copy: 
      src: index.html
      dest: /usr/share/nginx/html/index.html
      owner: root 
      group: root 
      mode: '0644'

  - name: Start Nginx
    systemd:
      name: nginx
      state: started
      enabled: true

  - name: Ensure nginx is running
    service:
      name: nginx
      state: started